server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/dmp_b2c_db
    hikari:
      maxLifetime: 180000
      maximumPoolSize: 24
      connectionTimeout: 1000
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    outOfOrder: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
