server:
  port: 8085
spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/msc-b2c-config
    hikari:
      maxLifetime: 180000
      maximumPoolSize: 24
      connectionTimeout: 1000
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    outOfOrder: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

# Sentry Config
sentry:
  dsn: https://920c6087e9664a93b2ec3cd01def4191@o1248805.ingest.sentry.io/6528342
  traces-sample-rate: 1.0
